export const RIGHT_READ = "read";
export const BOOLEAN_TRUE = "true";
export const JSON_EXT = "jsonExt";
export const CALCULATION_RULE = "calculation_rule";
export const OBJECT_FIELD_PATH_REGEX = /OBJECT(\.[a-zA-Z]*)*/g
export const OBJECT_FIELD_PATH_SEPARATOR = ".";
export const VARIABLE_NAME_SEPARATOR = "_";
export const INPUT_VARIABLE_NAME = "INPUT";
export const OBJECT_VARIABLE_NAME = "OBJECT";
export const CONTEXT_PRODUCT = "product";
export const CONTEXT_BENEFIT_PLAN = "benefit plan";
